backend:
  connectionString: "your-connectionString"
  image:
    repository: yurti/streetcode_back
    tag: latest
  replicas: 1
  urls: "https://0.0.0.0:5001"

frontend:
  enabled: true
  backUrl: /api
  image:
    repository: yurti/streetcode_cli
    tag: latest
  ContainerPort: 3000

